local Step=require"step";local A=require"ast";local V=require"visit";local U=require"util"
local AK=A.AstKind;local visitAst=V.visitAst;local shuffle=U.shuffle
local N=Step:extend()
N.Name="Numbers To Expressions"
N.Description="Converts number literals to arithmetic expressions"
N.SettingsDescriptor={Threshold={type="number",default=1,min=0,max=1},InternalThreshold={type="number",default=0.2,min=0,max=0.8},NumberRepresentationMutaton={type="boolean",default=false},AllowedNumberRepresentations={type="table",default={"hex","scientific","normal"}}}
local function genMod(n)local rhs=n+math.random(1,2^24);local mul=math.random(1,2^8);return n+(mul*rhs),rhs end
function N:init()self.ExpressionGenerators={function(val,depth)local v2=math.random(-2^20,2^20);local diff=val-v2;if tonumber(tostring(diff))+tonumber(tostring(v2))~=val then return false end;return A.AddExpression(self:CreateNumberExpression(v2,depth),self:CreateNumberExpression(diff,depth),false)end,function(val,depth)local v2=math.random(-2^20,2^20);local diff=val+v2;if tonumber(tostring(diff))-tonumber(tostring(v2))~=val then return false end;return A.SubExpression(self:CreateNumberExpression(diff,depth),self:CreateNumberExpression(v2,depth),false)end,function(val,depth)local lhs,rhs=genMod(val);if tonumber(tostring(lhs))%tonumber(tostring(rhs))~=val then return false end;return A.ModExpression(self:CreateNumberExpression(lhs,depth),self:CreateNumberExpression(rhs,depth),false)end}end
function N:CreateNumberExpression(val,depth)if depth>0 and math.random()>=self.InternalThreshold or depth>15 then local fmt=self.AllowedNumberRepresentations[math.random(#self.AllowedNumberRepresentations)];if not self.NumberRepresentationMutaton then return A.NumberExpression(val)end;if fmt=="hex" then if val~=math.floor(val)or val<0 then return A.NumberExpression(val)end;local s=string.format("0x%X",val);local r="";for i=1,#s do local c=s:sub(i,i);r=r..(math.random()>0.5 and c:upper()or c:lower())end;return A.NumberExpression(r)end;if fmt=="scientific" then if val==0 then return A.NumberExpression(val)end;local exp=math.floor(math.log10(math.abs(val)));local man=val/(10^exp);return A.NumberExpression(string.format("%.15ge%d",man,exp))end;return A.NumberExpression(val)end;local gens=shuffle({table.unpack(self.ExpressionGenerators)});for _,gen in ipairs(gens)do local n=gen(val,depth+1);if n then return n end end;return A.NumberExpression(val)end
function N:apply(ast)visitAst(ast,nil,function(node)if node.kind==AK.NumberExpression then if math.random()<=self.Threshold then return self:CreateNumberExpression(node.value,0)end end end)end
return N
