local U=require"util";local E=require"enums";local logger=require"logger"
local lk=U.lookupify;local ulk=U.unlookupify;local esc=U.escape;local ca=U.chararray
local T={}
T.EOF_CHAR="<EOF>"
T.WHITESPACE_CHARS=lk{" ","\t","\n","\r"}
T.ANNOTATION_CHARS=lk(ca("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"))
T.ANNOTATION_START_CHARS=lk(ca("!@"))
T.Conventions=E.Conventions
T.TokenKind={Eof="Eof",Keyword="Keyword",Symbol="Symbol",Ident="Identifier",Number="Number",String="String"}
T.EOF_TOKEN={kind="Eof",value="<EOF>",startPos=-1,endPos=-1,source="<EOF>"}
local function mk(self,sp,kind,value)local l,p=self:getPosition(self.index);local ann=self.annotations;self.annotations={};return{kind=kind,value=value,startPos=sp,endPos=self.index,source=self.source:sub(sp+1,self.index),line=l,linePos=p,annotations=ann}end
local function ge(self,msg)local l,p=self:getPosition(self.index);return"Lex Error at "..l..":"..p..", "..msg end
function T:getPosition(i)local col=self.columnMap[i]or self.columnMap[#self.columnMap];return col.id,col.charMap[i]end
function T:prepareGetPosition()local cm={};local col={charMap={},id=1,length=0};for idx=1,self.length do local c=self.source:sub(idx,idx);local cl=col.length+1;col.length=cl;col.charMap[idx]=cl;if c=="\n" then col={charMap={},id=col.id+1,length=0}end;cm[idx]=col end;self.columnMap=cm end
function T:new(s)local ver=(s and(s.luaVersion or s.LuaVersion))or"LuaU";local conv=T.Conventions[ver];if not conv then logger:error("Unknown Lua version: "..ver)end;local t={index=0,length=0,source="",luaVersion=ver,conventions=conv,NumberChars=conv.NumberChars,NumberCharsLookup=lk(conv.NumberChars),Keywords=conv.Keywords,KeywordsLookup=lk(conv.Keywords),BinaryNumberChars=conv.BinaryNumberChars,BinaryNumberCharsLookup=lk(conv.BinaryNumberChars),BinaryNums=conv.BinaryNums,HexadecimalNums=conv.HexadecimalNums,HexNumberChars=conv.HexNumberChars,HexNumberCharsLookup=lk(conv.HexNumberChars),DecimalExponent=conv.DecimalExponent,DecimalSeperators=conv.DecimalSeperators,IdentChars=conv.IdentChars,IdentCharsLookup=lk(conv.IdentChars),EscapeSequences=conv.EscapeSequences,NumericalEscapes=conv.NumericalEscapes,EscapeZIgnoreNextWhitespace=conv.EscapeZIgnoreNextWhitespace,HexEscapes=conv.HexEscapes,UnicodeEscapes=conv.UnicodeEscapes,SymbolChars=conv.SymbolChars,SymbolCharsLookup=lk(conv.SymbolChars),MaxSymbolLength=conv.MaxSymbolLength,Symbols=conv.Symbols,SymbolsLookup=lk(conv.Symbols),StringStartLookup=lk({"\"","'"}),annotations={}};setmetatable(t,self);self.__index=self;return t end
function T:reset()self.index=0;self.length=0;self.source="";self.annotations={};self.columnMap={}end
function T:append(code)self.source=self.source..code;self.length=self.length+#code;self:prepareGetPosition()end
local function pk(self,n)n=n or 0;local i=self.index+n+1;if i>self.length then return T.EOF_CHAR end;return self.source:sub(i,i)end
local function gt(self)local i=self.index+1;if i>self.length then logger:error(ge(self,"Unexpected end of input"))end;self.index=i;return self.source:sub(i,i)end
local function ex(self,c)if type(c)=="string" then c={[c]=true}end;local ch=pk(self);if not c[ch] then logger:error(ge(self,"Unexpected \""..esc(ch).."\""))end;self.index=self.index+1;return ch end
local function is(self,c,n)local ch=pk(self,n);if type(c)=="string" then return ch==c end;return c[ch]end
local function ri(self,chars,seps)local buf={};while true do if is(self,chars)then buf[#buf+1]=gt(self)elseif seps and is(self,seps)then self.index=self.index+1 else break end end;return table.concat(buf)end
function T:parseAnnotation()if is(self,T.ANNOTATION_START_CHARS)then self.index=self.index+1;local src,len={},0;while is(self,T.ANNOTATION_CHARS)do src[len+1]=gt(self);len=#src end;if len>0 then self.annotations[string.lower(table.concat(src))]=true end;return nil end;return gt(self)end
function T:skipComment()if is(self,"-",0)and is(self,"-",1)then self.index=self.index+2;if is(self,"[")then self.index=self.index+1;local eq=0;while is(self,"=")do self.index=self.index+1;eq=eq+1 end;if is(self,"[")then while true do if self:parseAnnotation()=="]" then local eq2=0;while is(self,"=")do self.index=self.index+1;eq2=eq2+1 end;if is(self,"]")and eq2==eq then self.index=self.index+1;return true end end end end end;while self.index<self.length and self:parseAnnotation()~="\n" do end;return true end;return false end
function T:skipWhitespaceAndComments()while self:skipComment()do end;while is(self,T.WHITESPACE_CHARS)do self.index=self.index+1;while self:skipComment()do end end end
function T:number()local sp=self.index;local src=ex(self,setmetatable({["."]=true},{__index=self.NumberCharsLookup}));if src=="0" then if self.BinaryNums and is(self,lk(self.BinaryNums))then self.index=self.index+1;local s=ri(self,self.BinaryNumberCharsLookup,self.DecimalSeperators and lk(self.DecimalSeperators)or nil);return mk(self,sp,T.TokenKind.Number,tonumber(s,2))end;if self.HexadecimalNums and is(self,lk(self.HexadecimalNums))then self.index=self.index+1;local s=ri(self,self.HexNumberCharsLookup,self.DecimalSeperators and lk(self.DecimalSeperators)or nil);return mk(self,sp,T.TokenKind.Number,tonumber(s,16))end end;local seps=self.DecimalSeperators and lk(self.DecimalSeperators)or nil;if src=="." then src=src..ri(self,self.NumberCharsLookup,seps)else src=src..ri(self,self.NumberCharsLookup,seps);if is(self,".")then src=src..gt(self)..ri(self,self.NumberCharsLookup,seps)end end;if self.DecimalExponent and is(self,lk(self.DecimalExponent))then src=src..gt(self);if is(self,lk({"+","-"}))then src=src..gt(self)end;local v=ri(self,self.NumberCharsLookup,seps);if#v<1 then logger:error(ge(self,"Expected valid exponent"))end;src=src..v end;return mk(self,sp,T.TokenKind.Number,tonumber(src))end
function T:ident()local sp=self.index;local src=ex(self,self.IdentCharsLookup);local parts={src};while is(self,self.IdentCharsLookup)do parts[#parts+1]=gt(self)end;src=table.concat(parts);if self.KeywordsLookup[src]then return mk(self,sp,T.TokenKind.Keyword,src)end;return mk(self,sp,T.TokenKind.Ident,src)end
function T:singleLineString()local sp=self.index;local sc=ex(self,self.StringStartLookup);local buf={};while not is(self,sc)do local c=gt(self);if c=="\n" then self.index=self.index-1;logger:error(ge(self,"Unterminated string"))end;if c=="\\" then c=gt(self);local e=self.EscapeSequences[c];if type(e)=="string" then c=e elseif self.NumericalEscapes and self.NumberCharsLookup[c]then local ns=c;if is(self,self.NumberCharsLookup)then ns=ns..gt(self)end;if is(self,self.NumberCharsLookup)then ns=ns..gt(self)end;c=string.char(tonumber(ns))elseif self.UnicodeEscapes and c=="u" then ex(self,"{");local num="";while is(self,self.HexNumberCharsLookup)do num=num..gt(self)end;ex(self,"}");c=U.utf8char(tonumber(num,16))elseif self.HexEscapes and c=="x" then local hex=ex(self,self.HexNumberCharsLookup)..ex(self,self.HexNumberCharsLookup);c=string.char(tonumber(hex,16))elseif self.EscapeZIgnoreNextWhitespace and c=="z" then c="";while is(self,T.WHITESPACE_CHARS)do self.index=self.index+1 end end end;buf[#buf+1]=c end;ex(self,sc);return mk(self,sp,T.TokenKind.String,table.concat(buf))end
function T:multiLineString()local sp=self.index;if is(self,"[")then self.index=self.index+1;local eq=0;while is(self,"=")do self.index=self.index+1;eq=eq+1 end;if is(self,"[")then self.index=self.index+1;if is(self,"\n")then self.index=self.index+1 end;local val="";while true do local c=gt(self);if c=="]" then local eq2=0;while is(self,"=")do c=c..gt(self);eq2=eq2+1 end;if is(self,"]")and eq2==eq then self.index=self.index+1;return mk(self,sp,T.TokenKind.String,val),true end end;val=val..c end end end;self.index=sp;return nil,false end
function T:symbol()local sp=self.index;for len=self.MaxSymbolLength,1,-1 do local str=self.source:sub(self.index+1,self.index+len);if self.SymbolsLookup[str]then self.index=self.index+len;return mk(self,sp,T.TokenKind.Symbol,str)end end;logger:error(ge(self,"Unknown symbol"))end
function T:next()self:skipWhitespaceAndComments();local sp=self.index;if sp>=self.length then return mk(self,sp,T.TokenKind.Eof)end;if is(self,self.NumberCharsLookup)then return self:number()end;if is(self,self.IdentCharsLookup)then return self:ident()end;if is(self,self.StringStartLookup)then return self:singleLineString()end;if is(self,"[",0)then local val,isS=self:multiLineString();if isS then return val end end;if is(self,".")and is(self,self.NumberCharsLookup,1)then return self:number()end;if is(self,self.SymbolCharsLookup)then return self:symbol()end;logger:error(ge(self,"Unexpected char \""..esc(pk(self)).."\""))end
function T:scanAll()local tb={};repeat local tk=self:next();tb[#tb+1]=tk until tk.kind==T.TokenKind.Eof;return tb end
return T
