local A=require"ast";local U=require"util"
local AK=A.AstKind;local lk=U.lookupify
local M={}
local compoundStats=lk{AK.CompoundAddStatement,AK.CompoundSubStatement,AK.CompoundMulStatement,AK.CompoundDivStatement,AK.CompoundModStatement,AK.CompoundPowStatement,AK.CompoundConcatStatement}
local binaryExprs=lk{AK.OrExpression,AK.AndExpression,AK.LessThanExpression,AK.GreaterThanExpression,AK.LessThanOrEqualsExpression,AK.GreaterThanOrEqualsExpression,AK.NotEqualsExpression,AK.EqualsExpression,AK.StrCatExpression,AK.AddExpression,AK.SubExpression,AK.MulExpression,AK.DivExpression,AK.ModExpression,AK.PowExpression}
local visitBlock,visitStatement,visitExpression
local function visitAst(ast,pre,post,data)ast.isAst=true;data=data or{};data.scopeStack={};data.functionData={depth=0,scope=ast.body.scope,node=ast};data.scope=ast.globalScope;data.globalScope=ast.globalScope;if type(pre)=="function" then local node,skip=pre(ast,data);ast=node or ast;if skip then return ast end end;visitBlock(ast.body,pre,post,data,true);if type(post)=="function" then ast=post(ast,data)or ast end;return ast end
visitBlock=function(block,pre,post,data,isFB)block.isBlock=true;block.isFunctionBlock=isFB or false;data.scope=block.scope;local pbd=data.blockData;data.blockData={};table.insert(data.scopeStack,block.scope);if type(pre)=="function" then local node,skip=pre(block,data);block=node or block;if skip then data.scope=table.remove(data.scopeStack);return block end end;local i=1;while i<=#block.statements do local stmt=table.remove(block.statements,i);i=i-1;local ret={visitStatement(stmt,pre,post,data)};for _,s in ipairs(ret)do i=i+1;table.insert(block.statements,i,s)end;i=i+1 end;if type(post)=="function" then block=post(block,data)or block end;data.scope=table.remove(data.scopeStack);data.blockData=pbd;return block end
visitStatement=function(stmt,pre,post,data)stmt.isStatement=true;if type(pre)=="function" then local node,skip=pre(stmt,data);stmt=node or stmt;if skip then return stmt end end;local k=stmt.kind;if k==AK.ReturnStatement then for i,e in ipairs(stmt.args)do stmt.args[i]=visitExpression(e,pre,post,data)end elseif k==AK.FunctionCallStatement or k==AK.PassSelfFunctionCallStatement then stmt.base=visitExpression(stmt.base,pre,post,data);for i,e in ipairs(stmt.args)do stmt.args[i]=visitExpression(e,pre,post,data)end elseif k==AK.AssignmentStatement then for i,e in ipairs(stmt.lhs)do stmt.lhs[i]=visitExpression(e,pre,post,data)end;for i,e in ipairs(stmt.rhs)do stmt.rhs[i]=visitExpression(e,pre,post,data)end elseif k==AK.FunctionDeclaration or k==AK.LocalFunctionDeclaration then local pfd=data.functionData;data.functionData={depth=pfd.depth+1,scope=stmt.body.scope,node=stmt};stmt.body=visitBlock(stmt.body,pre,post,data,true);data.functionData=pfd elseif k==AK.DoStatement then stmt.body=visitBlock(stmt.body,pre,post,data,false)elseif k==AK.WhileStatement then stmt.condition=visitExpression(stmt.condition,pre,post,data);stmt.body=visitBlock(stmt.body,pre,post,data,false)elseif k==AK.RepeatStatement then stmt.body=visitBlock(stmt.body,pre,post,data);stmt.condition=visitExpression(stmt.condition,pre,post,data)elseif k==AK.ForStatement then stmt.initialValue=visitExpression(stmt.initialValue,pre,post,data);stmt.finalValue=visitExpression(stmt.finalValue,pre,post,data);stmt.incrementBy=visitExpression(stmt.incrementBy,pre,post,data);stmt.body=visitBlock(stmt.body,pre,post,data,false)elseif k==AK.ForInStatement then for i,e in ipairs(stmt.expressions)do stmt.expressions[i]=visitExpression(e,pre,post,data)end;visitBlock(stmt.body,pre,post,data,false)elseif k==AK.IfStatement then stmt.condition=visitExpression(stmt.condition,pre,post,data);stmt.body=visitBlock(stmt.body,pre,post,data,false);for _,eif in ipairs(stmt.elseifs)do eif.condition=visitExpression(eif.condition,pre,post,data);eif.body=visitBlock(eif.body,pre,post,data,false)end;if stmt.elsebody then stmt.elsebody=visitBlock(stmt.elsebody,pre,post,data,false)end elseif k==AK.LocalVariableDeclaration then for i,e in ipairs(stmt.expressions)do stmt.expressions[i]=visitExpression(e,pre,post,data)end elseif compoundStats[k] then stmt.lhs=visitExpression(stmt.lhs,pre,post,data);stmt.rhs=visitExpression(stmt.rhs,pre,post,data)end;if type(post)=="function" then local stmts={post(stmt,data)};if#stmts>0 then return table.unpack(stmts)end end;return stmt end
visitExpression=function(expr,pre,post,data)expr.isExpression=true;if type(pre)=="function" then local node,skip=pre(expr,data);expr=node or expr;if skip then return expr end end;local k=expr.kind;if binaryExprs[k] then expr.lhs=visitExpression(expr.lhs,pre,post,data);expr.rhs=visitExpression(expr.rhs,pre,post,data)end;if k==AK.NotExpression or k==AK.NegateExpression or k==AK.LenExpression then expr.rhs=visitExpression(expr.rhs,pre,post,data)end;if k==AK.FunctionCallExpression or k==AK.PassSelfFunctionCallExpression then expr.base=visitExpression(expr.base,pre,post,data);for i,a in ipairs(expr.args)do expr.args[i]=visitExpression(a,pre,post,data)end end;if k==AK.FunctionLiteralExpression then local pfd=data.functionData;data.functionData={depth=pfd.depth+1,scope=expr.body.scope,node=expr};expr.body=visitBlock(expr.body,pre,post,data,true);data.functionData=pfd end;if k==AK.TableConstructorExpression then for _,entry in ipairs(expr.entries)do if entry.kind==AK.KeyedTableEntry then entry.key=visitExpression(entry.key,pre,post,data)end;entry.value=visitExpression(entry.value,pre,post,data)end end;if k==AK.IndexExpression or k==AK.AssignmentIndexing then expr.base=visitExpression(expr.base,pre,post,data);expr.index=visitExpression(expr.index,pre,post,data)end;if k==AK.IfElseExpression then expr.condition=visitExpression(expr.condition,pre,post,data);expr.true_value=visitExpression(expr.true_value,pre,post,data);expr.false_value=visitExpression(expr.false_value,pre,post,data)end;if type(post)=="function" then expr=post(expr,data)or expr end;return expr end
M.visitAst=visitAst;M.visitBlock=visitBlock;M.visitStatement=visitStatement;M.visitExpression=visitExpression
return M
